function sendForm(a){setProvinceInformation(a)}function setProvinceInformation(a){if(null==a)alert("Province not found.");else{var b=$("#taxes"),c=$("#attractions"),d=$("#result-default-msg"),e=$("#premier"),f=$("#province");var g="<h5>Tax Information:</h5>"+getTaxes(a);var h="<h5>Attractions:</h5>"+getAttractions(a);var k="<h5>Premier:</h5>"+getPremier(a);a="<h5>Province:</h5>"+getProvinceName(a);d.text("");b.append(g);c.append(h);e.append(k);f.append(a);b.focus()}}
function getTaxes(a){return"ON"==a?"Rate Type: HST, Total: 13%":"QC"==a?"Rate Type: GST + QST, Total: 14.975%":"NS"==a||"NB"==a?"Rate Type: HST, Total: 15%":"MB"==a?"Rate Type: GST+PST, Total: 13%":"BC"==a?"Rate Type: GST+PST, Total: 12%":"PE"==a?"Rate Type: HST, Total: 15%":"SK"==a?"Rate Type: GST + PST, Total: 11%":"AB"==a?"Rate Type: GST, Total: 5%":"NL"==a?"Rate Type: HST, Total: 15%":""}
function getProvinceName(a){return"ON"==a?"Ontario":"QC"==a?"Quebec":"NS"==a?"Nova Scotia":"NB"==a?"New Brunswick":"MB"==a?"Manitoba":"BC"==a?"British Columbia":"PE"==a?"Prince Edward Island":"SK"==a?"Saskatchewan":"AB"==a?"Alberta":"NL"==a?"Newfoundland and Labrador":""}
function getPremier(a){return"ON"==a?"Kathleen Wynne":"QC"==a?"Philippe Couillard":"NS"==a?"Stephen McNeil":"NB"==a?"Brian Gallant":"MB"==a?"Brian Pallister":"BC"==a?"John Horgan":"PE"==a?"Wade MacLauchlan":"SK"==a?"Scott Moe":"AB"==a?"Rachel Notley":"NL"==a?"Dwight Ball":""}function getAttractions(a){var b="";getAttractionsArray(a).forEach(function(a){b=b+a+"</br>"});return b}
function getAttractionsArray(a){var b=[];"ON"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):"QC"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):
"NS"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):"NB"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):
"MB"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):"BC"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):
"PE"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):"SK"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):
"AB"==a?(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>"):"NL"==a&&(b[0]="<a href='http://www.festivalsandeventsontario.ca/events/quinte-west-hops-on-the-water' target='_blank'>Quinte West Hops on the Water</a>",b[1]="<a href='http://www.festivalsandeventsontario.ca/events/stratford-festival' target='_blank'>Stratford Festival</a>");
return b};
